/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/config": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.config.id"];
          created_at?: parameters["rowFilter.config.created_at"];
          key?: parameters["rowFilter.config.key"];
          value?: parameters["rowFilter.config.value"];
          description?: parameters["rowFilter.config.description"];
          env?: parameters["rowFilter.config.env"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["config"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** config */
          config?: definitions["config"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.config.id"];
          created_at?: parameters["rowFilter.config.created_at"];
          key?: parameters["rowFilter.config.key"];
          value?: parameters["rowFilter.config.value"];
          description?: parameters["rowFilter.config.description"];
          env?: parameters["rowFilter.config.env"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.config.id"];
          created_at?: parameters["rowFilter.config.created_at"];
          key?: parameters["rowFilter.config.key"];
          value?: parameters["rowFilter.config.value"];
          description?: parameters["rowFilter.config.description"];
          env?: parameters["rowFilter.config.env"];
        };
        body: {
          /** config */
          config?: definitions["config"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/videoOnlyModeEnabled": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.videoOnlyModeEnabled.id"];
          created_at?: parameters["rowFilter.videoOnlyModeEnabled.created_at"];
          chat_id?: parameters["rowFilter.videoOnlyModeEnabled.chat_id"];
          enabled_at_day?: parameters["rowFilter.videoOnlyModeEnabled.enabled_at_day"];
          updated_at?: parameters["rowFilter.videoOnlyModeEnabled.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["videoOnlyModeEnabled"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** videoOnlyModeEnabled */
          videoOnlyModeEnabled?: definitions["videoOnlyModeEnabled"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.videoOnlyModeEnabled.id"];
          created_at?: parameters["rowFilter.videoOnlyModeEnabled.created_at"];
          chat_id?: parameters["rowFilter.videoOnlyModeEnabled.chat_id"];
          enabled_at_day?: parameters["rowFilter.videoOnlyModeEnabled.enabled_at_day"];
          updated_at?: parameters["rowFilter.videoOnlyModeEnabled.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.videoOnlyModeEnabled.id"];
          created_at?: parameters["rowFilter.videoOnlyModeEnabled.created_at"];
          chat_id?: parameters["rowFilter.videoOnlyModeEnabled.chat_id"];
          enabled_at_day?: parameters["rowFilter.videoOnlyModeEnabled.enabled_at_day"];
          updated_at?: parameters["rowFilter.videoOnlyModeEnabled.updated_at"];
        };
        body: {
          /** videoOnlyModeEnabled */
          videoOnlyModeEnabled?: definitions["videoOnlyModeEnabled"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description App-wide configuration */
  config: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    key: string;
    /** Format: text */
    value: string;
    /** Format: text */
    description?: string;
    /**
     * Format: character varying
     * @default production
     */
    env: string;
  };
  videoOnlyModeEnabled: {
    /** Format: bigint */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: character varying
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    chat_id: string;
    /** Format: character varying */
    enabled_at_day?: string;
    /**
     * Format: timestamp without time zone
     * @default now()
     */
    updated_at: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description config */
  "body.config": definitions["config"];
  /** Format: bigint */
  "rowFilter.config.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.config.created_at": string;
  /** Format: text */
  "rowFilter.config.key": string;
  /** Format: text */
  "rowFilter.config.value": string;
  /** Format: text */
  "rowFilter.config.description": string;
  /** Format: character varying */
  "rowFilter.config.env": string;
  /** @description videoOnlyModeEnabled */
  "body.videoOnlyModeEnabled": definitions["videoOnlyModeEnabled"];
  /** Format: bigint */
  "rowFilter.videoOnlyModeEnabled.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.videoOnlyModeEnabled.created_at": string;
  /** Format: character varying */
  "rowFilter.videoOnlyModeEnabled.chat_id": string;
  /** Format: character varying */
  "rowFilter.videoOnlyModeEnabled.enabled_at_day": string;
  /** Format: timestamp without time zone */
  "rowFilter.videoOnlyModeEnabled.updated_at": string;
}

export interface operations {}

export interface external {}
